-- ==============================================================================
-- SAHA TAKİP VE ŞANTİYE YÖNETİM SİSTEMİ - SUPABASE VERİTABANI ŞEMASI
-- ==============================================================================

-- 1. PERSONEL TABLOSU
CREATE TABLE IF NOT EXISTS public.personel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personel_no TEXT UNIQUE NOT NULL,
    sifre TEXT NOT NULL,
    ad TEXT NOT NULL,
    rol TEXT NOT NULL CHECK (rol IN ('patron', 'formen', 'personel')),
    gunluk_ucret NUMERIC(10, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. LOKASYONLAR (ŞANTİYELER) TABLOSU
CREATE TABLE IF NOT EXISTS public.lokasyonlar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad TEXT UNIQUE NOT NULL,
    enlem NUMERIC(10, 7),
    boylam NUMERIC(10, 7),
    yaricap_metre INTEGER DEFAULT 150,
    qr_kodu TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. GİRİŞ-ÇIKIŞ (MESAİ KAYITLARI) TABLOSU
CREATE TABLE IF NOT EXISTS public.giris_cikis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personel_no TEXT NOT NULL,
    ad TEXT NOT NULL,
    lokasyon TEXT NOT NULL,
    giris_saati TIMESTAMPTZ NOT NULL,
    cikis_saati TIMESTAMPTZ,
    sure_saat NUMERIC(6, 2),
    durum TEXT NOT NULL DEFAULT 'Açık' CHECK (durum IN ('Açık', 'Kapalı')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. MANUEL PUANTAJ DÜZELTMELERİ
CREATE TABLE IF NOT EXISTS public.puantaj_manuel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personel_no TEXT NOT NULL,
    tarih DATE NOT NULL,
    deger TEXT NOT NULL CHECK (deger IN ('1', '0.5', 'P', 'R', 'I')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT puantaj_manuel_personel_tarih_unique UNIQUE (personel_no, tarih)
);

-- 5. AYLIK FAZLA MESAİ SAATLERİ
CREATE TABLE IF NOT EXISTS public.aylik_fazla_mesai (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personel_no TEXT NOT NULL,
    yil INTEGER NOT NULL,
    ay INTEGER NOT NULL CHECK (ay BETWEEN 1 AND 12),
    saat NUMERIC(6, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT aylik_fazla_mesai_unique UNIQUE (personel_no, yil, ay)
);

-- 6. SAHA VERİLERİ (HARCAMA / AVANS / FİŞLER)
CREATE TABLE IF NOT EXISTS public.saha_verileri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personel_no TEXT NOT NULL,
    ad TEXT NOT NULL,
    lokasyon TEXT NOT NULL,
    kalem_turu TEXT NOT NULL,
    miktar NUMERIC(10, 2) NOT NULL,
    birim_fiyat NUMERIC(10, 2) NOT NULL,
    para_birimi TEXT DEFAULT 'PLN',
    toplam NUMERIC(10, 2) NOT NULL,
    aciklama TEXT,
    islem_turu TEXT NOT NULL DEFAULT 'harcama' CHECK (islem_turu IN ('harcama', 'avans')),
    fis_no TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. KALEM TÜRLERİ
CREATE TABLE IF NOT EXISTS public.kalem_turleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. ARAÇLAR TABLOSU
CREATE TABLE IF NOT EXISTS public.araclar (
    plaka TEXT PRIMARY KEY,
    marka TEXT,
    model TEXT,
    durum TEXT NOT NULL DEFAULT 'Boşta' CHECK (durum IN ('Boşta', 'Kullanımda', 'Bakımda')),
    son_km NUMERIC(10, 1) DEFAULT 0,
    resim_url TEXT,
    son_muayene_tarihi DATE,
    sonraki_muayene_tarihi DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. ARAÇ KULLANIM GEÇMİŞİ
CREATE TABLE IF NOT EXISTS public.arac_kullanim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personel_no TEXT NOT NULL,
    ad TEXT NOT NULL,
    plaka TEXT NOT NULL,
    alis_km NUMERIC(10, 1) NOT NULL,
    teslim_km NUMERIC(10, 1),
    katedilen_km NUMERIC(10, 1),
    durum TEXT NOT NULL DEFAULT 'Açık' CHECK (durum IN ('Açık', 'Kapalı')),
    tarih TIMESTAMPTZ DEFAULT NOW(),
    teslim_saati TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. GÖREVLER TABLOSU
CREATE TABLE IF NOT EXISTS public.gorevler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lokasyon TEXT NOT NULL,
    baslik TEXT NOT NULL,
    aciklama TEXT,
    oncelik TEXT NOT NULL DEFAULT 'Normal' CHECK (oncelik IN ('Düşük', 'Normal', 'Yüksek', 'Acil')),
    son_tarih DATE,
    atanan_personel_no JSONB DEFAULT '[]'::jsonb,
    atanan_adlar JSONB DEFAULT '[]'::jsonb,
    durum TEXT NOT NULL DEFAULT 'Bekliyor' CHECK (durum IN ('Bekliyor', 'Devam Ediyor', 'Tamamlandı')),
    olusturulma_tarihi TIMESTAMPTZ DEFAULT NOW(),
    tamamlanma_tarihi TIMESTAMPTZ,
    tamamlanma_foto_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. ŞANTİYE DEFTERLERİ (GÜNLÜK FAALİYET RAPORLARI)
CREATE TABLE IF NOT EXISTS public.santiye_defterleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tarih DATE DEFAULT CURRENT_DATE,
    saat TEXT,
    lokasyon TEXT NOT NULL,
    formen_no TEXT NOT NULL,
    formen_adi TEXT NOT NULL,
    hava_durumu TEXT DEFAULT 'Güneşli',
    sicaklik TEXT,
    saha_durumu TEXT DEFAULT 'Normal',
    saha_formen_sayisi INTEGER DEFAULT 0,
    saha_usta_sayisi INTEGER DEFAULT 0,
    saha_isci_sayisi INTEGER DEFAULT 0,
    ofis_personel_sayisi INTEGER DEFAULT 0,
    taseron_ekipleri JSONB DEFAULT '[]'::jsonb,
    arac_ekipman JSONB DEFAULT '[]'::jsonb,
    gelen_malzemeler JSONB DEFAULT '[]'::jsonb,
    bugun_yapilan TEXT NOT NULL,
    yarin_yapilacak TEXT,
    isg_durumu TEXT DEFAULT 'Kazasız Gün',
    isg_toolbox BOOLEAN DEFAULT true,
    isg_notlari TEXT,
    engeller_gecikmeler TEXT,
    notlar TEXT,
    fotograflar JSONB DEFAULT '[]'::jsonb,
    patron_onay TEXT DEFAULT 'Yeni' CHECK (patron_onay IN ('Yeni', 'Görüldü', 'Onaylandı', 'Revize İstendi')),
    patron_notu TEXT,
    patron_yarin_notu TEXT,
    durum TEXT NOT NULL DEFAULT 'Yeni' CHECK (durum IN ('Yeni', 'Görüldü')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Var olan santiye_defterleri tablosunu güvenle güncellemek için:
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS tarih DATE DEFAULT CURRENT_DATE;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS saat TEXT;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS hava_durumu TEXT DEFAULT 'Güneşli';
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS sicaklik TEXT;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS saha_durumu TEXT DEFAULT 'Normal';
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS taseron_ekipleri JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS gelen_malzemeler JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS isg_durumu TEXT DEFAULT 'Kazasız Gün';
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS isg_toolbox BOOLEAN DEFAULT true;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS isg_notlari TEXT;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS engeller_gecikmeler TEXT;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS fotograflar JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS patron_onay TEXT DEFAULT 'Yeni';
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS patron_notu TEXT;
ALTER TABLE public.santiye_defterleri ADD COLUMN IF NOT EXISTS patron_yarin_notu TEXT;

-- 12. PROJELER TABLOSU (MİMARİ PLANLAR)
CREATE TABLE IF NOT EXISTS public.projeler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lokasyon TEXT NOT NULL,
    baslik TEXT NOT NULL,
    resim_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. PROJE NOTLARI & HATA PİNLERİ
CREATE TABLE IF NOT EXISTS public.proje_notlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proje_id BIGINT REFERENCES public.projeler(id) ON DELETE CASCADE,
    x NUMERIC(6, 3) NOT NULL,
    y NUMERIC(6, 3) NOT NULL,
    aciklama TEXT NOT NULL,
    durum TEXT NOT NULL DEFAULT 'Açık' CHECK (durum IN ('Açık', 'Çözüldü')),
    olusturan TEXT NOT NULL,
    cozen TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. TEKLİFLER TABLOSU
CREATE TABLE IF NOT EXISTS public.teklifler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lokasyon TEXT NOT NULL,
    toplam_maliyet NUMERIC(12, 2) NOT NULL,
    teklif_metni TEXT NOT NULL,
    durum TEXT NOT NULL DEFAULT 'Onay Bekliyor' CHECK (durum IN ('Onay Bekliyor', 'Onaylandı', 'Reddedildi')),
    tarih TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. SİSTEM AYARLARI TABLOSU
CREATE TABLE IF NOT EXISTS public.sistem_ayarlari (
    id INTEGER PRIMARY KEY,
    konum_dogrulama_aktif BOOLEAN DEFAULT FALSE,
    qr_dogrulama_aktif BOOLEAN DEFAULT FALSE,
    gunluk_rapor_aktif BOOLEAN DEFAULT FALSE,
    haftalik_rapor_aktif BOOLEAN DEFAULT FALSE,
    aylik_rapor_aktif BOOLEAN DEFAULT FALSE,
    rapor_eposta TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- BAŞLANGIÇ VERİLERİ (SEED DATA)
-- ==============================================================================

-- 1. Varsayılan Ayarlar
INSERT INTO public.sistem_ayarlari (id, konum_dogrulama_aktif, qr_dogrulama_aktif, gunluk_rapor_aktif, haftalik_rapor_aktif, aylik_rapor_aktif, rapor_eposta)
VALUES (1, false, false, false, false, false, 'yonetim@firma.com')
ON CONFLICT (id) DO NOTHING;

-- 2. Varsayılan Personeller (Şifreler demo: 1234)
INSERT INTO public.personel (personel_no, sifre, ad, rol, gunluk_ucret) VALUES
('1000', '1234', 'Ahmet Yılmaz (Patron)', 'patron', 0),
('1001', '1234', 'Mehmet Demir (Formen)', 'formen', 350.00),
('1002', '1234', 'Ali Kaya (Usta)', 'personel', 250.00),
('1003', '1234', 'Can Yılmaz (İşçi)', 'personel', 200.00)
ON CONFLICT (personel_no) DO NOTHING;

-- 3. Varsayılan Lokasyonlar
INSERT INTO public.lokasyonlar (ad, enlem, boylam, yaricap_metre, qr_kodu) VALUES
('Merkez Şantiye - Varşova', 52.2297, 21.0122, 200, 'qr-lokasyon-varsowa-01'),
('Krakow Konut Projesi', 50.0647, 19.9450, 150, 'qr-lokasyon-krakow-02'),
('Gdansk Lojistik Depo', 54.3520, 18.6466, 250, 'qr-lokasyon-gdansk-03')
ON CONFLICT (ad) DO NOTHING;

-- 4. Varsayılan Kalem Türleri
INSERT INTO public.kalem_turleri (ad) VALUES
('Hazır Beton'),
('İnşaat Demiri'),
('Tuğla & Briket'),
('Kum / Çimento'),
('Yemek & İaşe'),
('Ulaşım & Akaryakıt'),
('Hırdavat & El Aleti')
ON CONFLICT (ad) DO NOTHING;

-- 5. Varsayılan Araçlar
INSERT INTO public.araclar (plaka, marka, model, durum, son_km, son_muayene_tarihi, sonraki_muayene_tarihi) VALUES
('WI 12345', 'Ford', 'Transit 350L', 'Boşta', 124500, '2025-01-15', '2026-01-15'),
('KR 98765', 'Mercedes-Benz', 'Sprinter', 'Boşta', 89300, '2025-03-10', '2026-03-10'),
('GD 45678', 'Renault', 'Master', 'Boşta', 156000, '2024-11-20', '2025-11-20')
ON CONFLICT (plaka) DO NOTHING;

-- ==============================================================================
-- REALTIME YAYIN AYARLARI (SUPABASE REALTIME ETKİNLEŞTİRME)
-- ==============================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.gorevler;
ALTER PUBLICATION supabase_realtime ADD TABLE public.santiye_defterleri;
ALTER PUBLICATION supabase_realtime ADD TABLE public.giris_cikis;
ALTER PUBLICATION supabase_realtime ADD TABLE public.arac_kullanim;
